'use client';

import { useState, useRef, useEffect } from 'react';
import Hls from 'hls.js';

// ==========================================
// 雙語字典 (Dictionary)
// ==========================================
const locales = {
  zh: {
    title: "Agora 直播與雲端錄製展示",
    coreSettings: "核心設定與操作",
    channelName: "房間名稱 (Channel)",
    tokenReadonly: "後端自動簽發 Token (唯讀)",
    tokenTitle: "由 Next.js 後端安全產生",
    s3UrlReadonly: "S3 雲端儲存路徑 (唯讀)",
    s3UrlTitle: "HLS 影片存檔位置",
    joinBtn: "加入頻道",
    leaveBtn: "離開頻道",
    startSttBtn: "開啟字幕",
    stopSttBtn: "停止字幕",
    startRecBtn: "開始錄製",
    stopRecBtn: "停止錄製",
    loadHlsBtn: "載入 HLS 回放",
    mediaMonitor: "影音即時監控與回放中心",
    localPreview: "本地端直播預覽 (RTC Live)",
    cloudPlayback: "雲端 HLS 回放模式",
    backToLive: "🔴 返回直播",
    systemLogs: "系統狀態日誌 (System Logs)",
    notJoined: "尚未加入頻道",
    cameraOff: "關閉鏡頭",
    cameraOn: "開啟鏡頭",
    mute: "靜音",
    unmute: "解除靜音",
    cameraMask: "鏡頭已關閉",
    clickLeftToLoad: "請點擊左側「載入 HLS 回放」按鈕",
    hlsNotLoaded: "未載入",
    hlsLoading: "連線中...",
    hlsPlaying: "LIVE (回放中)",
    hlsSafari: "LIVE (Safari原生)",
    hlsError: "載入失敗",
    hlsGenerating: "字幕快照生成中...",
    alertChannel: "請輸入房間名稱",
    alertStopFirst: "請先停止錄製與字幕任務後再離開頻道！",
    alertNoSid: "目前沒有錄製紀錄 (缺乏 SID)！請先開始錄製。",
    log: {
      reqToken: "向伺服器請求安全 Token 與系統參數...",
      initAgora: "初始化 Agora 連線...",
      joinSuccess: "✅ 已加入頻道！",
      leaveCheck: "準備離開頻道，正在檢查執行中的任務...",
      autoStopRec: "正在自動停止錄製任務...",
      autoStopRecSuccess: "✅ 自動停止錄製成功。",
      autoStopStt: "正在自動停止即時字幕...",
      autoStopSttSuccess: "✅ 自動停止字幕成功。",
      closeRtc: "正在關閉影音軌道與 RTC 連線...",
      leaveSuccess: "✅ 已完全離開頻道。",
      startStt: "啟動即時字幕...",
      startSttSuccess: "✅ 即時字幕已啟動！",
      stopStt: "正在停止即時字幕...",
      stopSttSuccess: "✅ 即時字幕已停止。",
      startRec: "啟動雲端錄製...",
      startRecSuccess: "✅ 雲端錄製已啟動！",
      stopRec: "正在停止錄製任務...",
      stopRecSuccess: "✅ 錄製已安全結束。",
      packVtt: "正在打包 VTT 字幕...",
      uploadVttSuccess: "✅ VTT 字幕檔成功上傳至 S3！",
      snapVtt: "正在產生即時字幕快照...",
      loadVtt: "錄製已結束，載入最終版 VTT 字幕...",
      errPrefix: "❌ 失敗:"
    }
  },
  en: {
    title: "Agora Live & Cloud Recording Demo",
    coreSettings: "Core Settings & Operations",
    channelName: "Channel Name",
    tokenReadonly: "Auto-Generated Token (Read-only)",
    tokenTitle: "Securely generated by Next.js Backend",
    s3UrlReadonly: "S3 Cloud Storage URL (Read-only)",
    s3UrlTitle: "HLS Video Storage Location",
    joinBtn: "Join Channel",
    leaveBtn: "Leave Channel",
    startSttBtn: "Start STT",
    stopSttBtn: "Stop STT",
    startRecBtn: "Start Recording",
    stopRecBtn: "Stop Recording",
    loadHlsBtn: "Load HLS Playback",
    mediaMonitor: "Media Monitor & Playback Center",
    localPreview: "Local Stream Preview (RTC Live)",
    cloudPlayback: "Cloud HLS Playback Mode",
    backToLive: "🔴 Back to Live",
    systemLogs: "System Logs",
    notJoined: "Not joined channel yet",
    cameraOff: "Turn Off Camera",
    cameraOn: "Turn On Camera",
    mute: "Mute",
    unmute: "Unmute",
    cameraMask: "Camera is off",
    clickLeftToLoad: "Please click 'Load HLS Playback' on the left",
    hlsNotLoaded: "Not Loaded",
    hlsLoading: "Connecting...",
    hlsPlaying: "LIVE (Playback)",
    hlsSafari: "LIVE (Safari Native)",
    hlsError: "Load Failed",
    hlsGenerating: "Generating VTT Snapshot...",
    alertChannel: "Please enter a channel name",
    alertStopFirst: "Please stop recording and STT before leaving the channel!",
    alertNoSid: "No recording record (Missing SID)! Please start recording first.",
    log: {
      reqToken: "Requesting secure Token and config from server...",
      initAgora: "Initializing Agora connection...",
      joinSuccess: "✅ Joined channel successfully!",
      leaveCheck: "Leaving channel, checking running tasks...",
      autoStopRec: "Auto-stopping recording task...",
      autoStopRecSuccess: "✅ Auto-stopped recording successfully.",
      autoStopStt: "Auto-stopping STT...",
      autoStopSttSuccess: "✅ Auto-stopped STT successfully.",
      closeRtc: "Closing media tracks and RTC connection...",
      leaveSuccess: "✅ Left channel completely.",
      startStt: "Starting Real-time STT...",
      startSttSuccess: "✅ Real-time STT started!",
      stopStt: "Stopping Real-time STT...",
      stopSttSuccess: "✅ Real-time STT stopped.",
      startRec: "Starting Cloud Recording...",
      startRecSuccess: "✅ Cloud Recording started!",
      stopRec: "Stopping recording task...",
      stopRecSuccess: "✅ Recording stopped safely.",
      packVtt: "Packaging VTT subtitles...",
      uploadVttSuccess: "✅ VTT file successfully uploaded to S3!",
      snapVtt: "Generating real-time VTT snapshot...",
      loadVtt: "Recording ended, loading final VTT subtitles...",
      errPrefix: "❌ Failed:"
    }
  }
};

export default function LiveDemoPage() {
  const [lang, setLang] = useState<'zh' | 'en'>('zh');
  const t = locales[lang];
  const tLog = t.log;

  const [channel, setChannel] = useState('');
  const [logs, setLogs] = useState<string[]>([]);
  
  const [isJoined, setIsJoined] = useState(false);
  const [isSttRunning, setIsSttRunning] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [hlsStatus, setHlsStatus] = useState(t.hlsNotLoaded);

  // ✨ 畫面檢視模式：'live' (即時預覽) 或 'playback' (雲端回放)
  const [viewMode, setViewMode] = useState<'live' | 'playback'>('live');

  const [isVideoEnabled, setIsVideoEnabled] = useState(true);
  const [isAudioMuted, setIsAudioMuted] = useState(false);
  const [displayToken, setDisplayToken] = useState('');
  const [displayS3Url, setDisplayS3Url] = useState('');

  const rtcRef = useRef<any>({ client: null, localAudioTrack: null, localVideoTrack: null });
  const tokenRef = useRef(''); 
  const sysConfigRef = useRef({ appId: '', s3BaseUrl: '' });
  const rttAgentIdRef = useRef(''); 
  const recRef = useRef({ resourceId: '', sid: '', uid: '' }); 
  const vttRef = useRef({ startTime: 0 as number | null, subtitles: [] as any[] });
  const hlsInstanceRef = useRef<any>(null);
  
  useEffect(() => {
    setChannel(`demo_${Math.random().toString(36).substring(2, 8)}`);
  }, []);

  const printLog = (msg: string) => {
    setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);
  };

  const fetchBackend = async (url: string, body: any, isText = false) => {
    const res = await fetch(url, {
      method: 'POST',
      headers: isText ? { 'X-File-Name': body.fileName } : { 'Content-Type': 'application/json' },
      body: isText ? body.text : JSON.stringify(body)
    });
    
    const contentType = res.headers.get("content-type");
    if (contentType && contentType.indexOf("application/json") !== -1) {
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || data.message || 'API Error');
      return data;
    } else {
      throw new Error(`Connection Error (${res.status})`);
    }
  };

  const getAgoraRTC = async () => {
    const module = await import('agora-rtc-sdk-ng');
    return module.default || module;
  };

  const formatVttTime = (ms: number) => {
    const hours = Math.floor(ms / 3600000);
    const minutes = Math.floor((ms % 3600000) / 60000);
    const seconds = Math.floor((ms % 60000) / 1000);
    const msStr = Math.floor(ms % 1000);
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(msStr).padStart(3, '0')}`;
  };

  const uploadVttSnapshot = async (sid: string) => {
    if (vttRef.current.subtitles.length === 0) return;
    printLog(tLog.packVtt);
    
    let vttString = "WEBVTT\n\n";
    vttRef.current.subtitles.forEach((sub, index) => {
        vttString += `${index + 1}\n${sub.start} --> ${sub.end}\n${sub.text}\n\n`;
    });

    try {
      const fileName = `cloudRecording/${sid}_${channel}.vtt`;
      await fetchBackend('/api/s3', { fileName, text: vttString }, true);
      printLog(tLog.uploadVttSuccess);
    } catch (e: any) {
      printLog(`${tLog.errPrefix} ${e.message}`);
    }
  };

  const handleStreamMessage = (uid: number, payload: Uint8Array) => {
    try {
      const textStr = new TextDecoder().decode(payload);
      const structMatch = textStr.match(/\n.([\u4e00-\u9fa5a-zA-Z0-9，。！？,.!?\s]+)\x10/);
      let cleanText = structMatch && structMatch[1] ? structMatch[1].trim() : "";
      
      cleanText = cleanText.replace(/transcribez?/gi, '').replace(/zh-?TW/gi, '').replace(/^[!！]+/, '').trim();

      if (cleanText.length > 1) {
        const subtitleEl = document.getElementById('global-subtitle-text');
        if (subtitleEl) {
          subtitleEl.innerText = cleanText;
          setTimeout(() => { subtitleEl.innerText = ""; }, 3000);
        }

        if (vttRef.current.startTime) {
            const currentMs = Date.now() - vttRef.current.startTime;
            const endMs = currentMs + 3000;
            const subs = vttRef.current.subtitles;
            const lastSub = subs[subs.length - 1];
            const isSameSentence = lastSub && (currentMs - lastSub.rawStartMs) < 1500 && !/[。！？.!?]$/.test(lastSub.text.trim());

            if (isSameSentence) {
                lastSub.text = cleanText;
                lastSub.end = formatVttTime(endMs);
                lastSub.rawEndMs = endMs; 
            } else {
                if (lastSub && lastSub.rawEndMs >= currentMs) {
                    lastSub.end = formatVttTime(currentMs - 1);
                    lastSub.rawEndMs = currentMs - 1;
                }
                subs.push({
                    rawStartMs: currentMs, rawEndMs: endMs,
                    start: formatVttTime(currentMs), end: formatVttTime(endMs), text: cleanText
                });
            }
        }
      }
    } catch (e) { console.warn(e); }
  };

  const toggleVideo = async () => {
    if (rtcRef.current.localVideoTrack) {
      await rtcRef.current.localVideoTrack.setEnabled(!isVideoEnabled);
      setIsVideoEnabled(!isVideoEnabled);
    }
  };

  const toggleAudio = async () => {
    if (rtcRef.current.localAudioTrack) {
      await rtcRef.current.localAudioTrack.setMuted(!isAudioMuted);
      setIsAudioMuted(!isAudioMuted);
    }
  };

  const toggleJoin = async () => {
    if (isJoined) {
      printLog(tLog.leaveCheck);

      if (isRecording) {
        printLog(tLog.autoStopRec);
        try {
          await fetchBackend('/api/agora', { action: 'stop-recording', channel, ...recRef.current });
          await uploadVttSnapshot(recRef.current.sid);
          setIsRecording(false);
          vttRef.current.startTime = null;
          printLog(tLog.autoStopRecSuccess);
        } catch (err: any) {
          printLog(`${tLog.errPrefix} ${err.message}`);
        }
      }

      if (isSttRunning) {
        printLog(tLog.autoStopStt);
        try {
          await fetchBackend('/api/agora', { action: 'stop-stt', agentId: rttAgentIdRef.current });
          setIsSttRunning(false);
          rttAgentIdRef.current = '';
          printLog(tLog.autoStopSttSuccess);
        } catch (err: any) {
          printLog(`${tLog.errPrefix} ${err.message}`);
        }
      }

      printLog(tLog.closeRtc);
      if (rtcRef.current.localAudioTrack) rtcRef.current.localAudioTrack.close();
      if (rtcRef.current.localVideoTrack) rtcRef.current.localVideoTrack.close();
      if (rtcRef.current.client) await rtcRef.current.client.leave();
      
      setIsJoined(false);
      tokenRef.current = ''; 
      
      setIsVideoEnabled(true);
      setIsAudioMuted(false);
      setDisplayToken('');
      setDisplayS3Url('');
      setHlsStatus(t.hlsNotLoaded);
      setViewMode('live'); // 離開時重置回直播視圖
      
      printLog(tLog.leaveSuccess);
    } else {
      if (!channel) return alert(t.alertChannel);
      try {
        printLog(tLog.reqToken);
        const tokenRes = await fetchBackend('/api/agora', { action: 'generate-token', channel });
        
        tokenRef.current = tokenRes.token;
        sysConfigRef.current.appId = tokenRes.appId;
        sysConfigRef.current.s3BaseUrl = tokenRes.s3BaseUrl;

        setDisplayToken(tokenRes.token);

        printLog(tLog.initAgora);
        const AgoraRTC = await getAgoraRTC();
        rtcRef.current.client = AgoraRTC.createClient({ mode: "live", codec: "vp8" });
        await rtcRef.current.client.setClientRole("host");
        rtcRef.current.client.on("stream-message", handleStreamMessage);
        
        await rtcRef.current.client.join(sysConfigRef.current.appId, channel, tokenRef.current, null);
        
        const [audio, video] = await AgoraRTC.createMicrophoneAndCameraTracks();
        rtcRef.current.localAudioTrack = audio;
        rtcRef.current.localVideoTrack = video;
        video.play("local-player");
        await rtcRef.current.client.publish([audio, video]);
        
        setIsJoined(true);
        printLog(tLog.joinSuccess);
      } catch (err: any) {
        printLog(`${tLog.errPrefix} ${err.message}`);
      }
    }
  };

  const toggleStt = async () => {
    if (isSttRunning) {
      printLog(tLog.stopStt);
      try {
        await fetchBackend('/api/agora', { action: 'stop-stt', agentId: rttAgentIdRef.current });
        setIsSttRunning(false);
        rttAgentIdRef.current = '';
        printLog(tLog.stopSttSuccess);
      } catch (err: any) {
        printLog(`${tLog.errPrefix} ${err.message}`);
      }
    } else {
      printLog(tLog.startStt);
      try {
        const sttRes = await fetchBackend('/api/agora', { action: 'start-stt', channel, token: tokenRef.current });
        rttAgentIdRef.current = sttRes.agent_id || sttRes.agentId;
        setIsSttRunning(true);
        printLog(tLog.startSttSuccess);
      } catch (err: any) {
        printLog(`${tLog.errPrefix} ${err.message}`);
      }
    }
  };

  const toggleRecording = async () => {
    if (isRecording) {
      printLog(tLog.stopRec);
      try {
        await fetchBackend('/api/agora', { action: 'stop-recording', channel, ...recRef.current });
        await uploadVttSnapshot(recRef.current.sid);
        
        setIsRecording(false);
        vttRef.current.startTime = null;
        printLog(tLog.stopRecSuccess);
      } catch (err: any) {
        printLog(`${tLog.errPrefix} ${err.message}`);
      }
    } else {
      printLog(tLog.startRec);
      try {
        vttRef.current.subtitles = []; 
        const recUid = String(Math.floor(Math.random() * 899999) + 100000);
        const acqRes = await fetchBackend('/api/agora', { action: 'acquire-recording', channel, uid: recUid });
        const recRes = await fetchBackend('/api/agora', { action: 'start-recording', channel, token: tokenRef.current, uid: recUid, resourceId: acqRes.resourceId });
        
        recRef.current = { resourceId: acqRes.resourceId, sid: recRes.sid, uid: recUid };
        vttRef.current.startTime = Date.now(); 
        
        const rawBaseUrl = sysConfigRef.current.s3BaseUrl || '';
        const baseUrl = rawBaseUrl.endsWith('/') ? rawBaseUrl : rawBaseUrl + '/';
        setDisplayS3Url(`${baseUrl}cloudRecording/${recRes.sid}_${channel}.m3u8`);

        setIsRecording(true);
        printLog(tLog.startRecSuccess);
      } catch (err: any) {
        printLog(`${tLog.errPrefix} ${err.message}`);
      }
    }
  };

  const loadPlayback = async () => {
    const sid = recRef.current.sid;
    if (!sid) return alert(t.alertNoSid);

    const rawBaseUrl = sysConfigRef.current.s3BaseUrl || '';
    const baseUrl = rawBaseUrl.endsWith('/') ? rawBaseUrl : rawBaseUrl + '/';
    
    const m3u8Url = `${baseUrl}cloudRecording/${sid}_${channel}.m3u8`;
    const vttUrl = `${baseUrl}cloudRecording/${sid}_${channel}.vtt?t=${Date.now()}`;

    const videoElement = document.getElementById("hls-video-player") as HTMLVideoElement;
    if (!videoElement) return;

    if (isRecording) {
      printLog(tLog.snapVtt);
      setHlsStatus(t.hlsGenerating);
      await uploadVttSnapshot(sid);
    } else {
      printLog(tLog.loadVtt);
    }

    // 清除舊的 track
    const oldTracks = videoElement.querySelectorAll("track");
    oldTracks.forEach(tr => tr.remove());

    const track = document.createElement("track");
    track.kind = "subtitles";
    track.label = lang === 'zh' ? "繁體中文" : "English";
    track.srclang = lang === 'zh' ? "zh-TW" : "en";
    track.src = vttUrl; 
    track.default = true;
    videoElement.appendChild(track);
    
    track.addEventListener("load", () => {
        if (videoElement.textTracks && videoElement.textTracks.length > 0) {
            videoElement.textTracks[0].mode = 'showing';
        }
    });

    if (hlsInstanceRef.current) hlsInstanceRef.current.destroy();
    setHlsStatus(t.hlsLoading);

    // ✨ 點擊載入後，自動切換至回放檢視模式（背景保持 RTC 連線）
    setViewMode('playback');

    if (Hls.isSupported()) {
      const hls = new Hls({ liveSyncDurationCount: 3 });
      hlsInstanceRef.current = hls;
      hls.loadSource(m3u8Url);
      hls.attachMedia(videoElement);
      
      hls.on(Hls.Events.MANIFEST_PARSED, () => {
        setHlsStatus(t.hlsPlaying);
        videoElement.play().catch(e => console.warn("Auto-play prevented", e));
      });

      hls.on(Hls.Events.ERROR, (event, data) => {
        if (data.fatal) {
          switch (data.type) {
            case Hls.ErrorTypes.NETWORK_ERROR:
              hls.startLoad();
              break;
            default:
              hls.destroy();
              setHlsStatus(t.hlsError);
              break;
          }
        }
      });
    } else if (videoElement.canPlayType('application/vnd.apple.mpegurl')) {
      videoElement.src = m3u8Url;
      videoElement.addEventListener('loadedmetadata', () => {
        videoElement.play();
        setHlsStatus(t.hlsSafari);
      });
    }
  };

  return (
    <div className="p-4 lg:p-8 max-w-[96%] mx-auto bg-gray-50 min-h-screen font-sans">
      {/* 標題與語系切換列 */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b pb-4 mb-6">
        <h1 className="text-3xl font-bold text-blue-600">{t.title}</h1>
        <button 
          onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')}
          className="mt-4 md:mt-0 px-4 py-2 bg-white border border-gray-300 rounded-full text-sm font-bold text-gray-700 hover:bg-gray-100 transition shadow-sm flex items-center gap-2"
        >
          <svg className="w-4 h-4 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129"></path></svg>
          {lang === 'zh' ? 'English' : '中文'}
        </button>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* 左側：控制面板區 */}
        <div className="lg:col-span-3 space-y-6">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 sticky top-8">
            <h2 className="text-lg font-bold text-gray-800 mb-4 flex items-center gap-2">
              <span className="w-1.5 h-6 bg-blue-500 rounded-full"></span> {t.coreSettings}
            </h2>
            
            <div className="space-y-4 mb-8">
              <div>
                <label className="block text-sm font-bold text-gray-700 mb-1">{t.channelName}</label>
                <input type="text" className="w-full border border-gray-300 p-2.5 rounded-lg text-gray-900 focus:ring-2 focus:ring-blue-500 text-sm bg-gray-50 font-mono" 
                  value={channel} onChange={e => setChannel(e.target.value)} disabled={isJoined} />
              </div>

              {displayToken && (
                <div>
                  <label className="block text-xs font-bold text-gray-500 mb-1">{t.tokenReadonly}</label>
                  <input type="text" className="w-full border border-gray-200 p-2.5 rounded-lg text-gray-400 text-xs bg-gray-50 font-mono cursor-not-allowed" 
                    value={displayToken} readOnly title={t.tokenTitle} />
                </div>
              )}
              {displayS3Url && (
                <div>
                  <label className="block text-xs font-bold text-gray-500 mb-1">{t.s3UrlReadonly}</label>
                  <textarea className="w-full border border-gray-200 p-2.5 rounded-lg text-gray-400 text-xs bg-gray-50 font-mono cursor-not-allowed resize-none" 
                    rows={3} value={displayS3Url} readOnly title={t.s3UrlTitle} />
                </div>
              )}
            </div>

            <div className="space-y-3">
              <button onClick={toggleJoin} className={`w-full py-3 rounded-lg text-white font-bold transition-colors shadow-sm ${isJoined ? 'bg-orange-500 hover:bg-orange-600' : 'bg-blue-600 hover:bg-blue-700'}`}>
                {isJoined ? t.leaveBtn : t.joinBtn}
              </button>
              
              <div className="grid grid-cols-2 gap-3">
                <button onClick={toggleStt} disabled={!isJoined} className={`w-full py-3 rounded-lg text-white font-bold transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed ${isSttRunning ? 'bg-yellow-500 hover:bg-yellow-600' : 'bg-emerald-500 hover:bg-emerald-600'}`}>
                  {isSttRunning ? t.stopSttBtn : t.startSttBtn}
                </button>
                <button onClick={toggleRecording} disabled={!isJoined} className={`w-full py-3 rounded-lg text-white font-bold transition-colors shadow-sm disabled:opacity-50 disabled:cursor-not-allowed ${isRecording ? 'bg-red-600 hover:bg-red-700' : 'bg-rose-500 hover:bg-rose-600'}`}>
                  {isRecording ? t.stopRecBtn : t.startRecBtn}
                </button>
              </div>

              <button onClick={loadPlayback} disabled={!recRef.current.sid} className="w-full py-3 mt-4 rounded-lg text-white font-bold transition-colors shadow-sm bg-purple-600 hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed">
                {t.loadHlsBtn}
              </button>
            </div>
          </div>
        </div>

        {/* 右側：整合型影音監控與回放區 (單一 View 切換模式) */}
        <div className="lg:col-span-9 space-y-6">
          
          <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-200">
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-md font-bold text-gray-800 flex items-center gap-2">
                <span className={`w-2 h-2 rounded-full ${viewMode === 'live' ? 'bg-blue-500' : 'bg-purple-500 animate-pulse'}`}></span> 
                {t.mediaMonitor}: <span className="text-blue-600">{viewMode === 'live' ? t.localPreview : t.cloudPlayback}</span>
              </h3>
              
              <div className="flex items-center gap-3">
                {/* 僅在直播模式且已加入時顯示音訊/鏡頭切換鈕 */}
                {isJoined && viewMode === 'live' && (
                  <div className="flex gap-2">
                    <button onClick={toggleAudio} className={`text-xs px-3 py-1.5 rounded border font-medium transition-colors ${isAudioMuted ? 'bg-red-50 text-red-600 border-red-200 hover:bg-red-100' : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'}`}>
                      {isAudioMuted ? t.unmute : t.mute}
                    </button>
                    <button onClick={toggleVideo} className={`text-xs px-3 py-1.5 rounded border font-medium transition-colors ${!isVideoEnabled ? 'bg-red-50 text-red-600 border-red-200 hover:bg-red-100' : 'bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100'}`}>
                      {!isVideoEnabled ? t.cameraOn : t.cameraOff}
                    </button>
                  </div>
                )}
                {isRecording && (
                  <div className="bg-red-600 text-white text-xs font-bold px-2 py-1.5 rounded flex items-center gap-1 animate-pulse">
                    <div className="w-1.5 h-1.5 bg-white rounded-full"></div> REC
                  </div>
                )}
              </div>
            </div>

            {/* 統一的影音外框容器 (position relative 確保內層元素與懸浮按鈕定位正確) */}
            <div className="bg-black w-full aspect-video rounded-lg relative overflow-hidden flex items-center justify-center border border-gray-800 shadow-inner">
               
               {/* 1. 未加入頻道的提示 */}
               {!isJoined && viewMode === 'live' && (
                 <div className="absolute inset-0 flex items-center justify-center text-gray-500 z-10 bg-black">
                   {t.notJoined}
                 </div>
               )}

               {/* 2. RTC 本地即時預覽 (切換至回放時使用 hidden 隱藏，保持 DOM 存活與連線) */}
               <div id="local-player" className={`w-full h-full absolute inset-0 ${viewMode === 'live' ? 'block' : 'hidden'}`}></div>
               
               {isJoined && !isVideoEnabled && viewMode === 'live' && (
                 <div className="absolute inset-0 flex items-center justify-center bg-gray-900 text-gray-400 z-10">
                   {t.cameraMask}
                 </div>
               )}

               {/* 3. HLS 回放影片播放器 (切換至直播時使用 hidden 隱藏) */}
               <video id="hls-video-player" className={`w-full h-full object-cover absolute inset-0 ${viewMode === 'playback' ? 'block' : 'hidden'}`} crossOrigin="anonymous" controls playsInline></video>
               
               {hlsStatus === t.hlsNotLoaded && viewMode === 'playback' && (
                  <div className="absolute inset-0 flex items-center justify-center text-gray-500 z-20 pointer-events-none">
                    {t.clickLeftToLoad}
                  </div>
               )}

               {/* 4. 即時字幕疊加層 (僅在直播模式作用) */}
               {viewMode === 'live' && (
                 <div className="absolute bottom-6 z-30 text-center w-full pointer-events-none">
                    <span id="global-subtitle-text" className="bg-black/70 text-green-400 px-3 py-1.5 rounded-lg text-md font-bold shadow-lg empty:hidden"></span>
                 </div>
               )}

               {/* 5. 懸浮按鈕：返回當前直播 (僅在回放模式顯示) */}
               {viewMode === 'playback' && (
                 <button 
                   onClick={() => {
                     // 1. 切換回直播檢視模式
                     setViewMode('live');
                     // 2. 抓取回放的 video 元素並將其暫停，避免背景漏音
                     const hlsVideo = document.getElementById("hls-video-player") as HTMLVideoElement;
                     if (hlsVideo && !hlsVideo.paused) {
                       hlsVideo.pause();
                     }
                   }}
                   className="absolute top-4 right-4 z-40 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2.5 rounded-lg font-bold shadow-xl transition-all flex items-center gap-2 animate-bounce cursor-pointer"
                 >
                   {t.backToLive}
                 </button>
               )}
            </div>
          </div>
          
          {/* 系統日誌區 */}
          <div className="bg-slate-50 border border-slate-300 p-4 rounded-xl text-sm font-mono h-48 overflow-y-auto shadow-inner text-slate-800">
            <div className="font-bold text-slate-500 mb-2 border-b border-slate-200 pb-2">{t.systemLogs}</div>
            {logs.map((log, i) => <div key={i} className="mb-1">{log}</div>)}
          </div>

        </div>
      </div>
    </div>
  );
}